name: grade12_math_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.2.7
  carousel_pro: ^0.0.13
  cupertino_icons: ^0.1.2
  pinch_zoom_image: "^0.2.5"
  photo_view: ^0.9.0
  flutter_plugin_pdf_viewer: 1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/
    - imagesh/
    - PAPER1/AM1/
    - PAPER1/AM2/
    - PAPER1/AQ1/
    - PAPER1/AQ2/
    - PAPER2/AM1/
    - PAPER2/AM2/
    - PAPER2/AQ1/
    - PAPER2/AQ2/
